version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/slack_googleAnalytics_integration

    steps:
      - checkout
      - run: npm install
      - run: node index.js
